spring.application.name=p3-1_resit

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=juice-shop-route
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:32768
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/**